global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: alertmanger
  static_configs:
  - targets:
    - 43.205.143.121:9093
- job_name: node_exporter
  static_configs:
  - targets:
    - 13.235.9.181:9100

alerting:
 alertmanagers:
  - static_configs:
    - targets:
      - 43.205.143.121:9093

rule_files:
  - "alert_rules.yml"